### ISSUE TITLE
Well Done, and a suggestion .... 

### ISSUE THREAD

**Issue by chuckm2000** [kg4vdk/arcos-linux-modules#10]
I have just done a test run of arcOS v21.3 on a laptop and I'm very impressed.  I have been a Linux/BSD/macOS/Windows user for many years, and this is one of the best implementations layered on top of Linux Mint I have ever seen.  Well done!  I can see why a non-computer-geek user could easily use this distro with little fuss getting it running.

A suggestion I'd love to see implemented ... an easy way to permanently install arcOS on the laptop's SSD without having to remove it to 'dd' the ISO directly to it.  Performance should be excellent on even a modest i5 CPU.

Many thanks for this, 73!
Chuck. VA7UL VA7ULD
va7ul@va7ul.ca

**Comment by kg4vdk** [comment]
Hey Chuck,

Thanks for the kind words and for testing it out! For installing to an internal SSD (which I do on my machines with less than plentiful USB ports), my method is to boot from an arcOS USB, with a copy of the ISO on board. Then, I use the "Disks" application to "Restore Disk Image" using the SSD as the target and the ISO as the source.

Heads up...this can make upgrading the ISO on the SSD difficult in the future, as the ISO-9660 signature is written to the SSD. This makes attempting to boot from a USB drive hard, because the system still sees a "bootable CDROM" signature on the SSD. My solution is to boot from the internal arcOS drive, and use the `fdisk` or `wipefs` utility to wipe the boot partition. Then, booting from the USB works as expected.

If I can come up with a clean way to make this easier for normal users, I'll certainly include it. Thanks for the input! I'm going to convert this issue to a discussion, so maybe others can weigh in.
