### ISSUE TITLE
Problems downloading, validating, and flashing India

### ISSUE THREAD

**Issue by daviesgeek** [kg4vdk/arcos-linux-modules#49]
I'm trying to download and flash India, but I'm having an issue once the ISO is downloaded [from SourceForge](https://sourceforge.net/projects/arcos-linux/). I'm downloading the latest ISO (the updated one from 2 weeks ago).

The ISO seems to download just fine, but when I check the MD5 hash, it's not the one provided on the website
Expected: `9d5eff5aba5da3d6b5fb4401f148b28b`
Received: `05412bf08f05b481dbe8e586073176bd2631c91d`
![image](https://github.com/user-attachments/assets/9e6509ec-5870-4b7e-beaf-ebec1c0c72b1)

I tried downloading a couple times and re-checking, but to the same result.

Then, when I use balenaEtcher to install it onto a USB drive, I get this error:

![image](https://github.com/user-attachments/assets/accfa1dd-845b-4b5e-b23a-aa79c056731a)

Is there something wrong with the ISO or am I doing something wrong?

**Comment by kg4vdk** [comment]
In your screenshot, it appears that you're generating the SHA1 checksum instead of the MD5 checksum.

`certutil -hashfile C:\Path\To\Downloaded\ISO\File.iso`
vs
`certutil -hashfile C:\Path\To\Downloaded\ISO\File.iso MD5`

Looking up the error you received in Balena Etcher points to several posts mentioning this can be the result of running Balena Etcher without Admin privileges.

**Comment by daviesgeek** [comment]
Thanks, i guess today is just my day to be computer illiterate :joy:. All fixed and good now!
